### PR TITLE
upgrade for cvxpy version 1.0.6 + cvxportfolio enhancements

### PR DESCRIPTION
**Pull request by weiyialanchen**

### CODE REVIEW

**Comment by weiyialanchen** [comment]
Going to add more stuffs and submit a new request

**Comment by weiyialanchen** [comment]
@enzobusseti @SteveDiamond 

Hi owners, would you mind helping review? Thanks.

**Comment by enzobusseti** [comment]
I can merge the min/max weights, but not the update to cvxpy 1.0. Can you make a pull request with only the first 4 commits? (The other commits you did will be used, just not now.)

**Comment by weiyialanchen** [comment]
Sure thanks. I will resubmit a pull request.

**Pull request closed without merging**
